# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
RUN pip3 install splunk-opentelemetry[all]
RUN splunk-py-trace-bootstrap

COPY . .

CMD [ "splunk-py-trace", "python3", "client.py"]

# client dockerfile
